fitness_for_all/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('shop/', include('shop.urls')),
    path('basket/', include('basket.urls')),
    path('workouts/', include('workouts.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
    path('member_blog/', include('member_blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.shop, name='shop'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/', views.delete_product, name='delete_product'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from shop.models import Product
from profiles.models import UserProfile

# Code taken from Code Institute Boutique Ado project


class Order(models.Model):
    order_number = models.TextField( null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, 
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    discount = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0

        self.delivery_cost = settings.STANDARD_DELIVERY_CHARGE

        self.grand_total = self.order_total + \
            self.delivery_cost - self.discount
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order, null=False, blank=False,
        on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False,
        blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, null=True, blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, 
        blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

shop/models.py
from django.db import models

# Code taken from Code Institute Boutique Ado project


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'
   
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

shop/forms.py
from django import forms
from .models import Product, Category

# Code taken from Code Institute Boutique Ado project


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

shop/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category
from .forms import ProductForm

# Create your views here.


def shop(request):
    """ View to return shop page """

    # code taken from Code Institute Boutique Ado walk through project
    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    category = "all_products"

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            category = categories[0]

            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('shop'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'
    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
        'category': category,
    }

    return render(request, 'shop/shop.html', context)


def product_detail(request, product_id):
    """ View to display product detail """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'shop/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to add product. \
                Please ensure the form is valid.')
    else:
        form = ProductForm()
        
    template = 'shop/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to update product. \
                    Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'shop/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product_id = (request.POST['product_id'])

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('shop'))

shop/templates/shop/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn_secondary btn-outline-black rounded-0" href="{% url 'shop' %}">Cancel</a>
                        <button class="btn btn-success btn-black rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

shop/templates/shop/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-secondary btn-outline-black rounded-0" href="{% url 'shop' %}">Cancel</a>
                        <button class="btn btn-success btn-black rounded-0" type="submit">Update Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

shop/templates/shop/product_detail.html
{%  extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">
{% endblock %}


{% block content %}
<div class="container h-100" >
    <div class="row h-100">   

    </div>
    <a class="{% if total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link" href="{% url 'basket' %}">
        <div class="text-right">
            <div><i class="fas fa-shopping-bag fa-lg"></i></div>
            <p class="my-0">
                {% if total %}
                    ${{ total|floatformat:2 }}
                {% else %}
                    $0.00
                {% endif %}
            </p>
        </div>
    </a>
</div>

<div class="container" id="prod_details">
    <div class="row" id="product_detail">
        <div class="col-sm-12 col-md-6">
            {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top h-100" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
            {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="No image available">
                </a>
            {% endif %}
        </div>
        <div class="col-sm-12 col-md-6">
            <h3>{{ product.name }}</h3>
            <p>{{ product.description }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            {% if request.user.is_authenticated %}  
                {% if request.user.is_superuser %}
                    <a href="{% url 'edit_product' product.id %}" class="btn btn-secondary">Edit</a>
                    <input type="hidden" id="product_id" name="product_id" value="{{ product.id }}">
                    <button class="del_prod btn btn-danger" type="submit"  data-toggle="modal" data-target="#delete_product_modal" >Delete</button>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <form class="form" action="{% url 'add_to_basket' product.id %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
                {% with product.has_sizes as s %}
                {% if s %}
                    <div class="col-12">
                        <p><strong>Size:</strong></p>
                        <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                            <option value="xs">XS</option>
                            <option value="s">S</option>
                            <option value="m" selected>M</option>
                            <option value="l">L</option>
                            <option value="xl">XL</option>
                        </select>
                    </div>
                {% endif %}
                <div class="col-12">
                    <p class="mt-3"><strong>Quantity:</strong></p>
                    <div class="form-group w-50">
                        <div class="input-group">
                            <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                        </div>
                    </div>
                </div>

                <div class="col-12 m-5">
                    <span class="icon">
                        <i class="fas fa-chevron-left"></i>
                    </span>
                    <a href="{% url 'shop' %}" class="btn rounded-0 text-uppercase btn btn-secondary">
                        Back to Shop
                    </a>
                    <button type="submit" class="btn btn-primary rounded-0 text-uppercase" value="Add to Basket">Add to Basket</button>
                </div>
                <input type="hidden" name="redirect_url" value="{{ request.path }}">
                {% endwith %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

shop/templates/shop/shop.html
{%  extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'shop/css/shop.css' %}">
{% endblock %}



{% block content %}
<div class="container h-100">
    <div class="row h-100">

        <form method="GET" action="{% url 'shop' %}">
            <div class="row input-group w-100 m-2">
                {% if search_term %}
                    <input class="col-sm-12 col-md-6 form-control border border-black rounded-0 m-2" type="text" name="q" value="{{ search_term }}">
                {% else %}
                    <input class="col-sm-12 col-md-6 form-control border border-black rounded-0 m-2" type="text" name="q" placeholder="Search">
                {% endif %}
                <div class="col-sm-6 col-md-3 input-group-append">
                    <button class="form-control btn btn-info m-2" id="search" type="submit">Search</button>
                    <a class="btn btn-secondary m-2" href="{% url 'shop' %}">RESET</a>
                    {% if request.user.is_authenticated %}   
                    {% if request.user.is_superuser %}
                        <a href="{% url 'add_product' %}" class="btn btn-success my-2 mx-5" id="add_product">Add Product</a>
                    {% endif %}
                {% endif %}
                </div>
            </div>
                <div class="row">
                <div class="col-6 m-2">
                    <select name="category_list" id="category_list" class="p-2">
                        <option value="reset" {% if category == 'all_proudcts' %}selected{% endif %}>All Products</option>   
                        <option value="equipment" {% if category == 'equipment' %}selected{% endif %}>Equipment</option>
                        <option value="clothing" {% if category == 'clothing' %}selected{% endif %}>Clothing</option>
                        <option value="accessories" {% if category == 'accessories' %}selected{% endif %}>Accessories</option>
                        <option value="nutrition" {% if category == 'nutrition' %}selected{% endif %}>Nutrition</option>                        
                    </select>
                    
                </div>

            <div class="col-6 m-2">
                <select name="sort_list" id="sort_list" class="p-2">
                    <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                    <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)</option>
                    <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)</option>
                    <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                    <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                </select>
            </div>
        </div>
        </form>
    </div>
    <a class="{% if total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link" href="{% url 'basket' %}">
        <div class="text-right">
            <div><i class="fas fa-shopping-bag fa-lg"></i></div>
            <p class="my-0">
                {% if total %}
                    ${{ total|floatformat:2 }}
                {% else %}
                    $0.00
                {% endif %}
            </p>
        </div>
    </a>
</div>

<div class="row">
    <div class="card-deck col-12 m-auto">
        {% for product in products %}
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 mb-2">
                <div class="card h-100" > 
                    <!-- Code snippet taken from Code Institute Boutique Ado walk through -->
                    {% if product.image %}
                        <a href="{% url 'product_detail' product.id %}">
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}" height="322">
                        </a>
                    {% else %}
                        <a href="{% url 'product_detail' product.id %}">
                            <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="No image available">
                        </a>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">£{{ product.price}}</p>
                    </div>
                
                    {% if request.user.is_authenticated %}  
                        {% if request.user.is_superuser %}
                            <div class="card-footer">
                                <a href="{% url 'edit_product' product.id %}" class="btn btn-secondary">Edit</a>
                                <input type="hidden" id="product_id{{ product.id}}" name="product_id" value="{{ product.id }}">
                                <button class="del_prod btn btn-danger" type="submit"  data-toggle="modal" data-target="#delete_product_modal">Delete</button>
                            </div>
                        {% endif %}
                    {% endif %}                     
                </div>
            </div>
        {% endfor %}
    </div>
</div>
 
{% endblock %}

{% block postload_js %}
    {{ block.super }}
    <script src="{% static 'shop/js/shop.js' %}"></script>
{% endblock %}



 